language: node_js

node_js:
- '10.6.0'
- '6'
- '7'
- '8'
- '9'

sudo: false

deploy:
- provider: script
  skip_cleanup: true
  script: npx semantic-release

env:
  global:
  - FORCE_COLOR=1
  - NPM_CONFIG_COLOR=always
